# Generated by Django 3.2.5 on 2021-07-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('icon', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('parent_market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='PostRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_rqst_slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('attachment', models.FileField(null=True, upload_to='files/')),
                ('budget', models.FloatField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.category')),
                ('delivery_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.deliverytime')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainApp.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Gigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_slug', models.SlugField(null=True)),
                ('title', models.CharField(max_length=240)),
                ('seo_title', models.CharField(max_length=50)),
                ('basic_title', models.CharField(max_length=120)),
                ('basic_desc', models.CharField(max_length=240)),
                ('basic_designCustom', models.BooleanField()),
                ('basic_contentUp', models.BooleanField()),
                ('basic_responsive', models.BooleanField()),
                ('basic_plugins', models.IntegerField()),
                ('basic_productsUp', models.IntegerField()),
                ('basic_ecommerc', models.BooleanField()),
                ('basic_revisions', models.IntegerField()),
                ('basic_price', models.FloatField()),
                ('standard_title', models.CharField(max_length=120)),
                ('standard_desc', models.CharField(max_length=240)),
                ('standard_designCustom', models.BooleanField()),
                ('standard_contentUp', models.BooleanField()),
                ('standard_responsive', models.BooleanField()),
                ('standard_plugins', models.IntegerField()),
                ('standard_productsUp', models.IntegerField()),
                ('standard_ecommerc', models.BooleanField()),
                ('standard_revisions', models.IntegerField()),
                ('standard_price', models.FloatField()),
                ('premium_title', models.CharField(max_length=120)),
                ('premium_desc', models.CharField(max_length=240)),
                ('premium_designCustom', models.BooleanField()),
                ('premium_contentUp', models.BooleanField()),
                ('premium_responsive', models.BooleanField()),
                ('premium_plugins', models.IntegerField()),
                ('premium_productsUp', models.IntegerField()),
                ('premium_ecommerc', models.BooleanField()),
                ('premium_revisions', models.IntegerField()),
                ('premium_price', models.FloatField()),
                ('description', models.TextField()),
                ('gallery_image', models.ImageField(null=True, upload_to='images/')),
                ('gallery_extra_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gallery_video', models.FileField(null=True, upload_to='videos/')),
                ('gig_click_count', models.PositiveIntegerField(default=0, null=True)),
                ('is_publish', models.BooleanField(default=False, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcategory')),
                ('tags', models.ManyToManyField(to='mainApp.Tag')),
            ],
        ),
    ]
