# Generated by Django 3.2.5 on 2021-07-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210726_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category'),
        ),
        migrations.AddField(
            model_name='gig',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.services'),
        ),
        migrations.AddField(
            model_name='gig',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcategory'),
        ),
    ]
