# Generated by Django 3.2.5 on 2021-07-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210715_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
