# Generated by Django 3.2.5 on 2021-07-15 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'png'])]),
        ),
    ]
